spring.profiles.active=@spring.profiles.active@

server.port=8081

spring.application.name=payment-validation-service





spring.datasource.hikari.maximum-pool-size=20

stripe.provider.createPaymentUrl=http://STRIPE-PROVIDER-SERVICE/v1/payments
stripe.api.key=sk_test_51Sx6HFC2d8oLw4onOKYYzb0EOsV4IAfeBI7qrqsdScGkdIy65j4rIGLHwcqhUSyDi6YdxwDyNWweHAcb8lQhTRpN00blC2GxK0
mytestkey=This value is from LOCAL properties file
# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/validation
spring.datasource.username=validation_user
spring.datasource.password=Gagan@2002
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#Hmac secret key
hmac.secret.key=THIS_IS_MY_SECRET

logging.level.org.springframework.security=TRACE

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
